version: '3.8'

services:
  vulnicheck:
    build: .
    image: vulnicheck:latest
    container_name: vulnicheck-mcp
    environment:
      - NVD_API_KEY=${NVD_API_KEY:-}
      - CACHE_TTL=${CACHE_TTL:-900}
      - REQUEST_TIMEOUT=${REQUEST_TIMEOUT:-30}
    stdin_open: true
    tty: true
    restart: unless-stopped
    # For development - mount the source code
    # volumes:
    #   - ./vulnicheck:/app/vulnicheck:ro